### ISSUE TITLE
what is ./data/LR_sample_5seq.mat

### ISSUE THREAD

**Issue by 531126085** [JihyongOh/FISR#2]
In the main.py file I found the following：
   ```
  """ to load a lighter train data to reduce time consumption """

      args.train_data_path = './data/LR_sample_5seq.mat'

      args.train_label_path = './data/HR_sample_5seq.mat'
```
what is ./data/LR_sample_5seq.mat，Where can i get them？
Without them, the program will report an error

**Comment by JihyongOh** [comment]
Hello, @531126085, 
sorry for your inconvenience because I missed those files.
Now I have uploaded those in ./data folder, so you can place them and get results.
Thank you for your interest on our work. 

Best regards,
Jihyong.
