### ISSUE TITLE
main.py: error:

### ISSUE THREAD

**Issue by jackxx33** [JihyongOh/FISR#21]
hello,why i have 
main.py: error: argument --phase: invalid choice: "'FISR_for_video'" (choose from 'train', 'test', 'FISR_for_video')
?

**Comment by JihyongOh** [comment]
Hello, @jackxx33 
Have you tried an option for --phase as 'FISR_for_video' as below?

```bash
python main.py --phase 'FISR_for_video' --exp_num 1 --frame_num 5 --frame_folder_path 'E:/FISR_Github/FISR_test_folder/scene1' --FISR_input_size (1080, 1920)
```

**Comment by jackxx33** [comment]
I don't know what “Insert(download) all our modified versions for ‘test’ and 'FISR_for_video' phase placed in the ‘FISR_tfoptflow’ folder.” means. Maybe something went wrong here.

**Comment by JihyongOh** [comment]
> yes,I tried ‘test’ and this is also the case,I copy your code directly to run.

That error can be possibly induced from the string format of OS for FISR_for_video as 'FISR_for_video', "FISR_for_video", FISR_for_video or a blank as ' ' etc. You may try these as well.

> I don't know what “Insert(download) all our modified versions for ‘test’ and 'FISR_for_video' phase placed in the ‘FISR_tfoptflow’ folder.” means. Maybe something went wrong here.

It means that all files in FISR_tfoptflow should be located as below figure. (keeping the file tree)

![image](https://user-images.githubusercontent.com/30177122/137672254-6c674e46-7d65-4fb7-ae7c-212856bb0c0d.png)
