### ISSUE TITLE
pretty bad PSNR and Result Image - Test Only

### ISSUE THREAD

**Issue by KeuntekLee** [JihyongOh/FISR#4]
Hi.
Thanks for uploading your codes.
However, i follow guide regarding only test, but it seems result images really bad and PSNR on logs are also bad.

Attach sample one result image and some logs below.
![pred_vid_1_fr_07171_seq_2](https://user-images.githubusercontent.com/39546106/75123597-31714980-56ec-11ea-98ed-3d6d5287c4be.png)

> Total size of variables: 48316251
Total bytes of variables: 193265004
Model: FISRnet
[*] Testing starts
 [*] Reading checkpoints...
WARNING:tensorflow:From /opt/conda/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
 [*] Success to read FISRnet-122000
 Start to read flow data (test).
Reading 10 x 8 x 1080 x 1920 x 2 flow file in .flo format
 Successfully load.
 Start to read warped data (test).
 Successfully load.
 <Test> [   0/  30]-th image, scene:  0-0, time: 1.0577(minutes), test_PSNR: fr1 (FI-SR) 13.82336405[dB], fr2 (SR) 14.73211411[dB], fr3 (FI-SR) 16.87715632[dB]
 --------------------------------------------------------------- test_SSIM: fr1 (FI-SR) 0.87482150, fr2 (SR) 0.78183737, fr3 (FI-SR) 0.86297231
 <Test> [   1/  30]-th image, scene:  0-1, time: 2.3114(minutes), test_PSNR: fr1 (FI-SR) 15.92068400[dB], fr2 (SR) 15.90569003[dB], fr3 (FI-SR) 16.80912121[dB]
 --------------------------------------------------------------- test_SSIM: fr1 (FI-SR) 0.85897002, fr2 (SR) 0.78195489, fr3 (FI-SR) 0.83428669
 <Test> [   2/  30]-th image, scene:  0-2, time: 3.5859(minutes), test_PSNR: fr1 (FI-SR) 17.18495496[dB], fr2 (SR) 15.63897788[dB], fr3 (FI-SR) 17.93267987[dB]

**Comment by KeuntekLee** [comment]
Plus, when i run test-only mode, it also find some flow, warp data about train.
Maybe something wrong condition branch on code.

**Comment by JihyongOh** [comment]
Hi, thank you for your interest.
After reading your comment, I have run the code again with same setting as mentioned, but have gotten same results. Did you check the requirements.txt? I saw your python version is 3.6 from the logs. Here are my logs are as below:

Total size of variables: 48316251
Total bytes of variables: 193265004
Model: FISRnet
[*] Testing starts
 [*] Reading checkpoints...
WARNING:tensorflow:From C:\Users\KAIST\Anaconda3\envs\tensorflow1.13new\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
 [*] Success to read FISRnet-122000
 Start to read flow data (test).
Reading 10 x 8 x 1080 x 1920 x 2 flow file in .flo format
 Successfully load.
 Start to read warped data (test).
 Successfully load.
 <Test> [   0/  30]-th image, scene:  0-0, time: 0.7282(minutes), test_PSNR: fr1 (FI-SR) 30.80811395[dB], fr2 (SR) 49.49890493[dB], fr3 (FI-SR) 30.88815544[dB]  
 --------------------------------------------------------------- test_SSIM: fr1 (FI-SR) 0.96549529, fr2 (SR) 0.99282218, fr3 (FI-SR) 0.96581642  
 <Test> [   1/  30]-th image, scene:  0-1, time: 1.5663(minutes), test_PSNR: fr1 (FI-SR) 30.90834178[dB], fr2 (SR) 49.76261276[dB], fr3 (FI-SR) 31.38353316[dB]  
 --------------------------------------------------------------- test_SSIM: fr1 (FI-SR) 0.96573934, fr2 (SR) 0.99291799, fr3 (FI-SR) 0.96657524  
 <Test> [   2/  30]-th image, scene:  0-2, time: 2.3919(minutes), test_PSNR: fr1 (FI-SR) 31.29300758[dB], fr2 (SR) 49.53979146[dB], fr3 (FI-SR) 31.82122443[dB]  
 --------------------------------------------------------------- test_SSIM: fr1 (FI-SR) 0.96635812, fr2 (SR) 0.99249411, fr3 (FI-SR) 0.96689562  
 <Test> [   3/  30]-th image, scene:  1-0, time: 3.2287(minutes), test_PSNR: fr1 (FI-SR) 40.22878873[dB], fr2 (SR) 51.42545004[dB], fr3 (FI-SR) 38.79654340[dB]  
 --------------------------------------------------------------- test_SSIM: fr1 (FI-SR) 0.97068584, fr2 (SR) 0.99430192, fr3 (FI-SR) 0.96435595  
 <Test> [   4/  30]-th image, scene:  1-1, time: 4.0769(minutes), test_PSNR: fr1 (FI-SR) 38.82801207[dB], fr2 (SR) 51.15768206[dB], fr3 (FI-SR) 37.75184344[dB]  
 --------------------------------------------------------------- test_SSIM: fr1 (FI-SR) 0.96431349, fr2 (SR) 0.99395041, fr3 (FI-SR) 0.95695764  
 <Test> [   5/  30]-th image, scene:  1-2, time: 4.9293(minutes), test_PSNR: fr1 (FI-SR) 37.87917766[dB], fr2 (SR) 51.29330409[dB], fr3 (FI-SR) 40.18696879[dB]  
 --------------------------------------------------------------- test_SSIM: fr1 (FI-SR) 0.95708952, fr2 (SR) 0.99403742, fr3 (FI-SR) 0.96968708  
 <Test> [   6/  30]-th image, scene:  2-0, time: 5.7835(minutes), test_PSNR: fr1 (FI-SR) 34.75822090[dB], fr2 (SR) 47.31346295[dB], fr3 (FI-SR) 36.81017214[dB]  
 --------------------------------------------------------------- test_SSIM: fr1 (FI-SR) 0.96880664, fr2 (SR) 0.99146217, fr3 (FI-SR) 0.97050954  
 <Test> [   7/  30]-th image, scene:  2-1, time: 6.6286(minutes), test_PSNR: fr1 (FI-SR) 37.51008909[dB], fr2 (SR) 47.77514762[dB], fr3 (FI-SR) 37.94192885[dB]  
 --------------------------------------------------------------- test_SSIM: fr1 (FI-SR) 0.97068121, fr2 (SR) 0.99125744, fr3 (FI-SR) 0.97142604  
 <Test> [   8/  30]-th image, scene:  2-2, time: 7.4665(minutes), test_PSNR: fr1 (FI-SR) 38.07522384[dB], fr2 (SR) 47.68251599[dB], fr3 (FI-SR) 37.71400016[dB]  
 --------------------------------------------------------------- test_SSIM: fr1 (FI-SR) 0.97125669, fr2 (SR) 0.99189483, fr3 (FI-SR) 0.97009078  
.......

**Comment by KeuntekLee** [comment]
Hi @JihyongOh 
Thanks for reply.
I guess i need to try set my environment same as yours(in requirements.txt)
After trying this, I'll update my comment.

**Comment by JihyongOh** [comment]
@KeuntekLee ,
Thank you for your reply, please note that we have also updated the requirements.txt file as we have uploaded new files in FISR_tfoptflow.

**Comment by KeuntekLee** [comment]
@JihyongOh 
I had set my tensorflow-gpu version as 1.13.1, however it still give me wrong same results.
and i don't think difference between python3.6 and 3.7 cause this issue.
Attach my options and command below, if there is something wrong, please let me know.

> python main.py --phase 'test' --exp_num 1 --test_data_path './data/test/LR_LFR' --test_flow_data_path './data/test/flow/LR_Surfing_SlamDunk_test_ss1.flo' --test_warped_data_path './data/test/warped/LR_Surfing_SlamDunk_test_ss1_warp.mat' --test_label_path './data/test/HR_HFR'


> net_type : FISRnet
fraction_gpu : 1.0
phase : test
scale_factor : 2
train_data_path : ./data/LR_sample_5seq.mat
train_flow_data_path : ./data/train/flow/LR_Surfing_SlamDunk_5seq_ss1.flo
train_flow_ss2_data_path : ./data/train/flow/LR_Surfing_SlamDunk_5seq_ss2.flo
train_warped_data_path : ./data/train/warped/LR_Surfing_SlamDunk_5seq_ss1_warp.mat
train_wapred_ss2_data_path : ./data/train/warped/LR_Surfing_SlamDunk_5seq_ss2_warp.mat
train_label_path : ./data/HR_sample_5seq.mat
test_data_path : ./data/test/LR_LFR
test_flow_data_path : ./data/test/flow/LR_Surfing_SlamDunk_test_ss1.flo
test_warped_data_path : ./data/test/warped/LR_Surfing_SlamDunk_test_ss1_warp.mat
test_label_path : ./data/test/HR_HFR
test_img_dir : ./test_img_dir
text_dir : ./text_dir
checkpoint_dir : ./checkpoint_dir
log_dir : ./logdir
exp_num : 1
epoch : 100
freq_display : 100
init_lr : 0.0001
lr_type : stair_decay
lr_stair_decay_points : [80, 90]
lr_decreasing_factor : 0.1
lr_linear_decay_point : 50
batch_size : 8
n_train_img_showed : 3
val_batch_size : 2
val_data_size : 320
recn_lambda : 1.0
tm1_lambda : 1.0
tm2_lambda : 0.1
tmm_lambda : 1.0
td_lambda : 0.1
ss2_lambda : 1.0
test_patch : (2, 2)
test_input_size : (1080, 1920)
frame_folder_path : E:/FISR_Github/FISR_test_folder/scene1
frame_num : 60
FISR_test_patch : (2, 2)
[*] Exp:  1
[*] Building FISRnet ...
 Start to read 4K data.
/opt/conda/lib/python3.6/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)
 Successfully load.
 Start to read flow data.
Reading 10086 x 8 x 96 x 96 x 2 flow file in .flo format
Reading 10086 x 4 x 96 x 96 x 2 flow file in .flo format

**Comment by JihyongOh** [comment]
@KeuntekLee 
Yes, I think so, besides, your attached commands are same as us. 
There is an one possibility related to GPU capacity issue. 

May you regulate "--test_patch (2,2)"  into smaller patches like (3,2), (3,3), (4,4),  so on?
According to our experience, sometimes we got dummy results like you got, in smaller GPU capacity setting.

**Comment by Pea-Shooter** [comment]
> Plus, when i run test-only mode, it also find some flow, warp data about train.
> Maybe something wrong condition branch on code.

I also got this problem and it cost a huge memory.

**Comment by JihyongOh** [comment]
@Pea-Shooter, @KeuntekLee 
Thank you for your suggestion, 
I modified the both "main.py" and "FISRnet.py" for not loading the flow & warp data related to 'train' mode when running a 'test' or 'FISR_for_video' mode.

**Comment by JihyongOh** [comment]
@KeuntekLee,
please refer this [reply ](https://github.com/JihyongOh/FISR/issues/8#issuecomment-638668040).
Thank you.
