### ISSUE TITLE
No module named 'FISR_tfoptflow.ckpt_mgr'

### ISSUE THREAD

**Issue by Pea-Shooter** [JihyongOh/FISR#5]
in model_base.py line 18

` from .ckpt_mgr import BestCheckpointSaver`
 
where is the module ckpt_mgr?

**Comment by Pea-Shooter** [comment]
and also missed the module TFSR_tfoptflow.utils and TFSR_tfoptflow.lr?

**Comment by JihyongOh** [comment]
Hello, 
As we described in 'Description', 

"you can download all the related tensorflow files from **this link** including weights, and then modify the folder name ‘tfoptflow’ as ‘FISR_tfoptflow’. Insert(download) all our modified versions for ‘test’ and 'FISR_for_video' phase placed in the ‘FISR_tfoptflow’ folder.""

Thank you:)

**Comment by Pea-Shooter** [comment]
Thanks for your reply! Finally, I ran your code successfully. 
But I still have some suggestions for you :

1. Without the code mentioned above, your code is incomplete and cannot run successfully as you import them in some other files, so I recommend you submit the whole code.
2. Maybe add a shell command (or a bash script) instead of only a complex introduction of all args would be more clear for readers.

It would be very appreciated if you can do this.
