### ISSUE TITLE
Result problem

### ISSUE THREAD

**Issue by Yangxiaojun1230** [JihyongOh/FISR#7]
Hi author,
I run below.
python main.py --phase 'FISR_for_video' --exp_num 1 --frame_num 3 --frame_folder_path './FISR_test_folder/scene1'
The result image size was (2048,3840) ,but only quarter of original image. 
My purpose is to run SR on single image .
Did you have any idea about the problem

**Comment by JihyongOh** [comment]
Hello,
What does "The result image size was (2048,3840) ,but only quarter of original image." means?
I follow your command that "python main.py --phase 'FISR_for_video' --exp_num 1 --frame_num 3 --frame_folder_path", and I have gotten results as below.

![image](https://user-images.githubusercontent.com/30177122/78221063-a01ca080-74fd-11ea-8c7f-69ccfee46e44.png)

**Comment by Yangxiaojun1230** [comment]
Hi author,
Thanks for your reply, I could run example correctly at the end , since I added the code to save the images.Whatever it works.
But I have another question, could this lib do work on single picture?

**Comment by JihyongOh** [comment]
No, because the input of the provided network must be composed of three consequent frames, four bidirectional flows and four warped frames.

**Comment by Yangxiaojun1230** [comment]
Thanks
