### ISSUE TITLE
Training set in PNG format

### ISSUE THREAD

**Issue by ObeliskChoi** [JihyongOh/FISR#8]
Thanks for your excellent work and your 4K dataset. 
1. I would like to train other VFI and SR models on your 4K dataset to evaluate their performance on UHD videos. Could you upload the source .png files of the training set?
2. I ran the test code but got bad results similar to https://github.com/JihyongOh/FISR/issues/4. Following your suggestion, I regulated "--test_patch (2,2)" into smaller patches (4,4) but got no improvement. The experiments were conducted in Centos. Is there anything wrong when running in Linux?
Thank you.

**Comment by TMYuan** [comment]
I  found add "sorted()" in [line 762](https://github.com/JihyongOh/FISR/blob/0ec490340258755d255b39bcb2814ccbe7764f6c/FISRnet.py#L762) and 763 in FISRnet.py can solve question 2.

**Comment by ObeliskChoi** [comment]
> I found add "sorted()" in [line 762](https://github.com/JihyongOh/FISR/blob/0ec490340258755d255b39bcb2814ccbe7764f6c/FISRnet.py#L762) and 763 in FISRnet.py can solve question 2.
It works! Thanks for your help!

**Comment by ObeliskChoi** [comment]
> I found add "sorted()" in [line 762](https://github.com/JihyongOh/FISR/blob/0ec490340258755d255b39bcb2814ccbe7764f6c/FISRnet.py#L762) and 763 in FISRnet.py can solve question 2.

It works! Thanks for your help!

**Comment by JihyongOh** [comment]
@ObeliskChoi 
sorry for late replies.

1. Since the capacity of raw png files are quite large, you can directly download via a [site](https://4kmedia.org/). We downloaded the two videos named "[Sony 4K Surfing](https://4kmedia.org/sony-surfing-uhd-4k-demo/)" and "[LG Slam Dunk 4K Demo](https://4kmedia.org/lg-slam-dunk-uhd-4k-demo/)". 

2. Thankfully, @TMYuan  solved the problem, so we have reflected it in the code.

**Comment by ObeliskChoi** [comment]
> @ObeliskChoi
> sorry for late replies.
> 
> 1. Since the capacity of raw png files are quite large, you can directly download via a [site](https://4kmedia.org/). We downloaded the two videos named "[Sony 4K Surfing](https://4kmedia.org/sony-surfing-uhd-4k-demo/)" and "[LG Slam Dunk 4K Demo](https://4kmedia.org/lg-slam-dunk-uhd-4k-demo/)".
> 2. Thankfully, @TMYuan  solved the problem, so we have reflected it in the code.

Thanks for your help!
